language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install: 
  - cpanm --quiet --installdeps --notest --force --skip-satisfied .
env: RELEASE_TESTING=1 AUTOMATED_TESTING=1

# Report coverage only once
jobs:
  include:
    - stage: deploy
      script:
        - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Coveralls
        - perl Build.PL && ./Build build && cover -test
        - cover -report coveralls
      perl: 5.26

